version: "2"
services:
  ushahidi:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CACHE_DRIVER: redis
    networks:
      - ushnw
  mysql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
    networks:
      - ushnw
  redis:
    image: redis:5-alpine
    networks:
      - ushnw
networks:
  ushnw:
    driver: bridge
